package service

import (
	"backend-go/internal/models"
	"fmt"
	"strings"
)

type ExportService struct{}

func NewExportService() *ExportService {
	return &ExportService{}
}

func (s *ExportService) GenerateSQL(graph *models.SimilarityGraph) string {
	var sb strings.Builder

	sb.WriteString("-- Generated by Project Euler\n")
	sb.WriteString("-- SQL Query to join File 1 and File 2 based on high-confidence mappings\n\n")
	sb.WriteString("SELECT\n")

	// Select fields (mocking table names as table1 and table2)
	sb.WriteString("    t1.*,\n")
	sb.WriteString("    t2.*\n")
	sb.WriteString("FROM table1 t1\n")
	sb.WriteString("JOIN table2 t2 ON\n")

	first := true
	for _, sim := range graph.Similarities {
		if sim.Confidence >= 70.0 { // Only high confidence
			if !first {
				sb.WriteString("    AND ")
			} else {
				sb.WriteString("    ")
			}
			sb.WriteString(fmt.Sprintf("t1.%s = t2.%s\n", sim.File1Column, sim.File2Column))
			first = false
		}
	}

	if first {
		sb.WriteString("    1 = 1 -- No high confidence relationships found\n")
	}

	return sb.String()
}

func (s *ExportService) GeneratePython(graph *models.SimilarityGraph) string {
	var sb strings.Builder

	sb.WriteString("# Generated by Project Euler\n")
	sb.WriteString("import pandas as pd\n\n")

	sb.WriteString("# Load your data\n")
	sb.WriteString("df1 = pd.read_csv('file1.csv')\n")
	sb.WriteString("df2 = pd.read_csv('file2.csv')\n\n")

	sb.WriteString("# Merge DataFrames\n")
	sb.WriteString("merged_df = pd.merge(\n")
	sb.WriteString("    df1,\n")
	sb.WriteString("    df2,\n")
	sb.WriteString("    left_on=[\n")

	// Left keys
	for _, sim := range graph.Similarities {
		if sim.Confidence >= 70.0 {
			sb.WriteString(fmt.Sprintf("        '%s',\n", sim.File1Column))
		}
	}
	sb.WriteString("    ],\n")
	sb.WriteString("    right_on=[\n")

	// Right keys
	for _, sim := range graph.Similarities {
		if sim.Confidence >= 70.0 {
			sb.WriteString(fmt.Sprintf("        '%s',\n", sim.File2Column))
		}
	}
	sb.WriteString("    ],\n")
	sb.WriteString("    how='inner'\n")
	sb.WriteString(")\n\n")
	sb.WriteString("print(merged_df.head())\n")

	return sb.String()
}
